stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests"

build_job:
  stage: build
  image: maven:3.8.7-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test_job:
  stage: test
  image: maven:3.8.7-eclipse-temurin-17
  script:
    - mvn test
